# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.huggingface.depth_estimation
from nodetool.workflows.base_node import BaseNode


class DepthEstimation(SingleOutputGraphNode[types.ImageRef], GraphNode[types.ImageRef]):
    """

    Estimates depth from a single image.
    image, depth estimation, 3D, huggingface

    Use cases:
    - Generate depth maps for 3D modeling
    - Assist in augmented reality applications
    - Enhance computer vision systems for robotics
    - Improve scene understanding in autonomous vehicles
    """

    model: types.HFDepthEstimation | OutputHandle[types.HFDepthEstimation] = (
        connect_field(
            default=types.HFDepthEstimation(
                type="hf.depth_estimation",
                repo_id="LiheYoung/depth-anything-base-hf",
                path=None,
                variant=None,
                allow_patterns=None,
                ignore_patterns=None,
            ),
            description="The model ID to use for depth estimation",
        )
    )
    image: types.ImageRef | OutputHandle[types.ImageRef] = connect_field(
        default=types.ImageRef(type="image", uri="", asset_id=None, data=None),
        description="The input image for depth estimation",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.huggingface.depth_estimation.DepthEstimation

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
