# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.huggingface.depth_estimation
from nodetool.workflows.base_node import BaseNode


class DepthEstimation(SingleOutputGraphNode[types.ImageRef], GraphNode[types.ImageRef]):
    """

    Generates depth maps from single RGB images using monocular depth estimation models.
    image, depth-estimation, 3D, huggingface, computer-vision

    Use cases:
    - Create depth maps for 3D modeling and scene reconstruction
    - Enable augmented reality applications with depth awareness
    - Improve robotic navigation and obstacle detection
    - Enhance scene understanding in autonomous vehicles
    - Generate depth-based visual effects for images and video
    """

    model: types.HFDepthEstimation | OutputHandle[types.HFDepthEstimation] = (
        connect_field(
            default=types.HFDepthEstimation(
                type="hf.depth_estimation",
                repo_id="LiheYoung/depth-anything-base-hf",
                path=None,
                variant=None,
                allow_patterns=None,
                ignore_patterns=None,
            ),
            description="The depth estimation model to use. Depth-Anything V2 models offer state-of-the-art accuracy; DPT-large is a reliable alternative.",
        )
    )
    image: types.ImageRef | OutputHandle[types.ImageRef] = connect_field(
        default=types.ImageRef(
            type="image", uri="", asset_id=None, data=None, metadata=None
        ),
        description="The input RGB image to estimate depth from. Any standard image format is supported.",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.huggingface.depth_estimation.DepthEstimation

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
