# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.huggingface.feature_extraction
from nodetool.workflows.base_node import BaseNode


class FeatureExtraction(SingleOutputGraphNode[types.NPArray], GraphNode[types.NPArray]):
    """

    Extracts dense vector embeddings from text using transformer models for downstream ML tasks.
    text, feature-extraction, embeddings, NLP, semantic-search

    Use cases:
    - Compute text embeddings for semantic similarity comparisons
    - Cluster documents by meaning rather than keywords
    - Generate input features for machine learning classifiers
    - Build semantic search engines and recommendation systems
    - Create vector databases for retrieval-augmented generation (RAG)
    """

    model: types.HFFeatureExtraction | OutputHandle[types.HFFeatureExtraction] = (
        connect_field(
            default=types.HFFeatureExtraction(
                type="hf.feature_extraction",
                repo_id="",
                path=None,
                variant=None,
                allow_patterns=None,
                ignore_patterns=None,
            ),
            description="The embedding model to use. mxbai-embed-large-v1 and BGE models offer excellent quality; smaller models trade accuracy for speed.",
        )
    )
    inputs: str | OutputHandle[str] = connect_field(
        default="",
        description="The text to extract embeddings from. Can be a sentence, paragraph, or document.",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.huggingface.feature_extraction.FeatureExtraction

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
