# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.huggingface.fill_mask
from nodetool.workflows.base_node import BaseNode


class FillMask(SingleOutputGraphNode[dict[str, Any]], GraphNode[dict[str, Any]]):
    """

    Fills in a masked token in a given text.
    text, fill-mask, natural language processing

    Use cases:
    - Text completion
    - Sentence prediction
    - Language understanding tasks
    - Generating text options
    """

    model: types.HFFillMask | OutputHandle[types.HFFillMask] = connect_field(
        default=types.HFFillMask(
            type="hf.fill_mask",
            repo_id="",
            path=None,
            variant=None,
            allow_patterns=None,
            ignore_patterns=None,
        ),
        description="The model ID to use for fill-mask task",
    )
    inputs: str | OutputHandle[str] = connect_field(
        default="The capital of France is [MASK].",
        description="The input text with [MASK] token to be filled",
    )
    top_k: int | OutputHandle[int] = connect_field(
        default=5, description="Number of top predictions to return"
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.huggingface.fill_mask.FillMask

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
