# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.huggingface.image_to_3d
from nodetool.workflows.base_node import BaseNode


class Hunyuan3D(SingleOutputGraphNode[types.Model3DRef], GraphNode[types.Model3DRef]):
    """

    Generate 3D meshes from images using Tencent Hunyuan3D-2 or 2.1.
    3d, generation, image-to-3d, hunyuan3d, mesh, local, high-quality

    Use cases:
    - Generate 3D models from images locally
    - Create 3D assets from product photos or concept art
    - Convert single images to 3D meshes
    - Prototype 3D content without API costs

    Produces untextured meshes (shape only). Use external tools for texturing.

    **Platforms:** Linux+CUDA, Windows+CUDA. Installable on macOS but does not run.

    **Requirements:** hy3dgen>=2.0.2 package, torch with CUDA.
    First run downloads ~5GB model (shape-only, not full repo).
    Standard/2.1 models need ~6–8GB VRAM, mini needs ~5GB. Use low_vram_mode on constrained GPUs.

    Models: https://huggingface.co/tencent/Hunyuan3D-2
            https://huggingface.co/tencent/Hunyuan3D-2.1
    """

    ModelVariant: typing.ClassVar[type] = (
        nodetool.nodes.huggingface.image_to_3d.Hunyuan3D.ModelVariant
    )
    OutputFormat: typing.ClassVar[type] = (
        nodetool.nodes.huggingface.image_to_3d.Hunyuan3D.OutputFormat
    )

    image: types.ImageRef | OutputHandle[types.ImageRef] = connect_field(
        default=types.ImageRef(
            type="image", uri="", asset_id=None, data=None, metadata=None
        ),
        description="Input image to convert to 3D",
    )
    model_variant: nodetool.nodes.huggingface.image_to_3d.Hunyuan3D.ModelVariant = (
        Field(
            default=nodetool.nodes.huggingface.image_to_3d.Hunyuan3D.ModelVariant.STANDARD,
            description="Model variant. Standard v2.0 (1.1B params, ~6GB VRAM, most stable), Mini v2.0 (0.6B params, ~5GB VRAM, fastest), or V2.1 (3.3B params, best quality, ~8GB VRAM — requires hy3dgen>=2.1; with hy3dgen 2.0.x V2.1 weights may fail to load or crash mid-inference).",
        )
    )
    num_inference_steps: int | OutputHandle[int] = connect_field(
        default=30,
        description="Number of denoising steps. More steps = better quality but slower.",
    )
    guidance_scale: float | OutputHandle[float] = connect_field(
        default=5.0,
        description="How strongly to follow the input. Higher = more adherence.",
    )
    octree_resolution: int | OutputHandle[int] = connect_field(
        default=256,
        description="Resolution of the octree for mesh extraction. Higher = more detail but uses more VRAM and is more likely to crash on Windows. 256 is a safe default; 384+ requires plenty of VRAM.",
    )
    low_vram_mode: bool | OutputHandle[bool] = connect_field(
        default=False,
        description="Enable CPU offloading for GPUs with less than 8GB VRAM.",
    )
    output_format: nodetool.nodes.huggingface.image_to_3d.Hunyuan3D.OutputFormat = (
        Field(
            default=nodetool.nodes.huggingface.image_to_3d.Hunyuan3D.OutputFormat.GLB,
            description="Output format for the 3D model. GLB is recommended; OBJ files are not previewable in the canvas viewer.",
        )
    )
    seed: int | OutputHandle[int] = connect_field(
        default=-1, description="Random seed for reproducibility. -1 for random."
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.huggingface.image_to_3d.Hunyuan3D

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.huggingface.image_to_3d
from nodetool.workflows.base_node import BaseNode


class ShapEImageTo3D(
    SingleOutputGraphNode[types.Model3DRef], GraphNode[types.Model3DRef]
):
    """

    Generate 3D models from images using OpenAI Shap-E.
    3d, generation, image-to-3d, shap-e, mesh, local, reconstruction

    Use cases:
    - Convert images to 3D models locally
    - Create 3D assets from product photos
    - Generate 3D content without API costs
    - Reconstruct 3D objects from single images

    **Platforms:** all (CPU/MPS/CUDA).

    **Note:** Requires diffusers and torch. First run will download the model (~2.5GB).
    """

    image: types.ImageRef | OutputHandle[types.ImageRef] = connect_field(
        default=types.ImageRef(
            type="image", uri="", asset_id=None, data=None, metadata=None
        ),
        description="Input image to convert to 3D",
    )
    guidance_scale: float | OutputHandle[float] = connect_field(
        default=3.0,
        description="How strongly to follow the image. Higher = more image adherence.",
    )
    num_inference_steps: int | OutputHandle[int] = connect_field(
        default=64,
        description="Number of denoising steps. More steps = better quality but slower.",
    )
    frame_size: int | OutputHandle[int] = connect_field(
        default=256,
        description="Resolution of the internal representation. Higher = more detail.",
    )
    seed: int | OutputHandle[int] = connect_field(
        default=-1, description="Random seed for reproducibility. -1 for random."
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.huggingface.image_to_3d.ShapEImageTo3D

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.huggingface.image_to_3d
from nodetool.workflows.base_node import BaseNode


class StableFast3D(
    SingleOutputGraphNode[types.Model3DRef], GraphNode[types.Model3DRef]
):
    """

    Generate textured 3D meshes from images in under 1 second using Stability AI SF3D.
    3d, generation, image-to-3d, sf3d, mesh, local, fast, textured

    Use cases:
    - Ultra-fast 3D asset generation from images
    - Create game-ready 3D assets with textures
    - Generate UV-unwrapped meshes with materials
    - Real-time 3D reconstruction workflows

    **Platforms:** Linux+CUDA, Windows+CUDA. macOS Metal experimental (untested, slow).

    **Requirements:** sf3d package, rembg, torch. CUDA recommended; Metal/CPU experimental.
    First run downloads ~1GB model. Needs ~6GB VRAM on CUDA.
    Generates textured meshes with UV maps, normal maps, and PBR materials.

    Model: https://huggingface.co/stabilityai/stable-fast-3d
    License: Free for <$1M revenue, enterprise license required above.
    """

    OutputFormat: typing.ClassVar[type] = (
        nodetool.nodes.huggingface.image_to_3d.StableFast3D.OutputFormat
    )

    image: types.ImageRef | OutputHandle[types.ImageRef] = connect_field(
        default=types.ImageRef(
            type="image", uri="", asset_id=None, data=None, metadata=None
        ),
        description="Input image to convert to 3D",
    )
    foreground_ratio: float | OutputHandle[float] = connect_field(
        default=0.85,
        description="Ratio of foreground size to image size after background removal.",
    )
    texture_resolution: int | OutputHandle[int] = connect_field(
        default=1024, description="Resolution of the texture atlas."
    )
    remesh: bool | OutputHandle[bool] = connect_field(
        default=False, description="Whether to remesh the output for cleaner topology."
    )
    output_format: nodetool.nodes.huggingface.image_to_3d.StableFast3D.OutputFormat = (
        Field(
            default=nodetool.nodes.huggingface.image_to_3d.StableFast3D.OutputFormat.GLB,
            description="Output format for the 3D model. GLB is recommended; OBJ files are not previewable in the canvas viewer.",
        )
    )
    low_vram_mode: bool | OutputHandle[bool] = connect_field(
        default=False,
        description="Enable CPU offloading for GPUs with less than 8GB VRAM.",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.huggingface.image_to_3d.StableFast3D

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.huggingface.image_to_3d
from nodetool.workflows.base_node import BaseNode


class Trellis2(SingleOutputGraphNode[types.Model3DRef], GraphNode[types.Model3DRef]):
    """

    Generate high-fidelity 3D models from images using Microsoft TRELLIS.2-4B.
    3d, generation, image-to-3d, trellis, mesh, local, high-quality, PBR, o-voxel

    Use cases:
    - Generate state-of-the-art 3D models from single images
    - Create production-ready 3D assets with PBR materials
    - Handle complex topology including open surfaces and non-manifold geometry
    - Generate assets with transparency/translucency support

    **Platforms:** Linux+CUDA only, 24 GB+ VRAM.

    **Note:** Requires trellis2, o_voxel, torch, and 24GB+ GPU memory.
    Currently only tested on Linux systems.
    First run will download the model (~10GB+).

    Model: https://huggingface.co/microsoft/TRELLIS.2-4B
    Paper: https://arxiv.org/abs/2512.14692
    """

    Resolution: typing.ClassVar[type] = (
        nodetool.nodes.huggingface.image_to_3d.Trellis2.Resolution
    )

    image: types.ImageRef | OutputHandle[types.ImageRef] = connect_field(
        default=types.ImageRef(
            type="image", uri="", asset_id=None, data=None, metadata=None
        ),
        description="Input image to convert to 3D",
    )
    resolution: nodetool.nodes.huggingface.image_to_3d.Trellis2.Resolution = Field(
        default=nodetool.nodes.huggingface.image_to_3d.Trellis2.Resolution.RES_1024,
        description="Voxel grid resolution. Higher = more detail but slower. 512 (~3s), 1024 (~17s), 1536 (~60s) on H100.",
    )
    decimation_target: int | OutputHandle[int] = connect_field(
        default=1000000,
        description="Target number of faces for mesh decimation. Lower = smaller file size.",
    )
    texture_size: int | OutputHandle[int] = connect_field(
        default=4096, description="Texture resolution for PBR materials."
    )
    remesh: bool | OutputHandle[bool] = connect_field(
        default=True, description="Whether to remesh the output for cleaner topology."
    )
    seed: int | OutputHandle[int] = connect_field(
        default=-1, description="Random seed for reproducibility. -1 for random."
    )
    low_vram_mode: bool | OutputHandle[bool] = connect_field(
        default=False,
        description="Reserved for future use. TRELLIS.2 upstream does not currently support CPU offloading.",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.huggingface.image_to_3d.Trellis2

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.huggingface.image_to_3d
from nodetool.workflows.base_node import BaseNode


class TripoSG(SingleOutputGraphNode[types.Model3DRef], GraphNode[types.Model3DRef]):
    """

    Generate high-fidelity 3D meshes from images using VAST TripoSG.
    3d, generation, image-to-3d, triposg, mesh, local, high-fidelity, rectified-flow

    Use cases:
    - Generate detailed 3D models from single images
    - Create 3D assets from photos, cartoons, or sketches
    - Produce meshes with sharp geometric features and fine surface details
    - Handle complex topology including thin structures

    **Platforms:** Linux+CUDA, Windows+CUDA (build required).

    **Requirements:** CUDA GPU with at least 8GB VRAM.
    First run downloads ~3GB model weights.

    Model: https://huggingface.co/VAST-AI/TripoSG
    License: MIT
    """

    image: types.ImageRef | OutputHandle[types.ImageRef] = connect_field(
        default=types.ImageRef(
            type="image", uri="", asset_id=None, data=None, metadata=None
        ),
        description="Input image to convert to 3D",
    )
    num_inference_steps: int | OutputHandle[int] = connect_field(
        default=50,
        description="Number of denoising steps. More steps = better quality but slower.",
    )
    guidance_scale: float | OutputHandle[float] = connect_field(
        default=7.0,
        description="Classifier-free guidance scale. Higher = more adherence to input.",
    )
    octree_depth: int | OutputHandle[int] = connect_field(
        default=7,
        description="Octree depth for mesh extraction. Higher = finer detail but slower. 7 is a good balance (~30s). 9 gives maximum detail but requires diso for speed.",
    )
    max_faces: int | OutputHandle[int] = connect_field(
        default=-1,
        description="Maximum number of faces in output mesh. -1 for no limit.",
    )
    seed: int | OutputHandle[int] = connect_field(
        default=-1, description="Random seed for reproducibility. -1 for random."
    )
    low_vram_mode: bool | OutputHandle[bool] = connect_field(
        default=False,
        description="Enable CPU offloading for GPUs with less than 10GB VRAM.",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.huggingface.image_to_3d.TripoSG

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.huggingface.image_to_3d
from nodetool.workflows.base_node import BaseNode


class TripoSR(SingleOutputGraphNode[types.Model3DRef], GraphNode[types.Model3DRef]):
    """

    Generate 3D meshes from images using Stability AI TripoSR.
    3d, generation, image-to-3d, triposr, mesh, local, fast

    Use cases:
    - Fast 3D reconstruction from single images
    - Generate 3D models from concept art
    - Create 3D assets for games and visualization
    - Prototype 3D content quickly

    **Platforms:** Linux+CUDA, Windows+CUDA. macOS CPU experimental (slow, untested).

    **Requirements:** tsr package (TripoSR), rembg, torch. CUDA recommended; CPU/MPS experimental.
    First run downloads ~1GB model. Needs ~6GB VRAM on CUDA.

    Model: https://huggingface.co/stabilityai/TripoSR
    License: MIT
    """

    OutputFormat: typing.ClassVar[type] = (
        nodetool.nodes.huggingface.image_to_3d.TripoSR.OutputFormat
    )

    image: types.ImageRef | OutputHandle[types.ImageRef] = connect_field(
        default=types.ImageRef(
            type="image", uri="", asset_id=None, data=None, metadata=None
        ),
        description="Input image to convert to 3D",
    )
    foreground_ratio: float | OutputHandle[float] = connect_field(
        default=0.85,
        description="Ratio of foreground size to image size after background removal.",
    )
    mc_resolution: int | OutputHandle[int] = connect_field(
        default=256,
        description="Marching cubes resolution for mesh extraction. Higher = more detail.",
    )
    output_format: nodetool.nodes.huggingface.image_to_3d.TripoSR.OutputFormat = Field(
        default=nodetool.nodes.huggingface.image_to_3d.TripoSR.OutputFormat.GLB,
        description="Output format for the 3D model. GLB is recommended; OBJ files are not previewable in the canvas viewer.",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.huggingface.image_to_3d.TripoSR

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
