# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.huggingface.ranking
from nodetool.workflows.base_node import BaseNode


class Reranker(SingleOutputGraphNode[dict[str, float]], GraphNode[dict[str, float]]):
    """

    Scores and ranks text pairs by semantic relevance using cross-encoder reranking models.
    text, ranking, reranking, NLP, search

    Use cases:
    - Improve search result quality by reranking initial retrieval results
    - Score question-answer pair relevance for QA systems
    - Rank document relevance for information retrieval
    - Build two-stage retrieval pipelines (retrieve then rerank)
    - Filter and prioritize candidates in recommendation systems
    """

    model: types.HFReranker | OutputHandle[types.HFReranker] = connect_field(
        default=types.HFReranker(
            type="hf.reranker",
            repo_id="",
            path=None,
            variant=None,
            allow_patterns=None,
            ignore_patterns=None,
        ),
        description="The reranking model. BGE-reranker-v2-m3 is multilingual; base and large variants offer different speed/accuracy tradeoffs.",
    )
    query: str | OutputHandle[str] = connect_field(
        default="", description="The query or question to compare candidates against."
    )
    candidates: list[str] | OutputHandle[list[str]] = connect_field(
        default=[],
        description="List of text candidates to rank by relevance to the query.",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.huggingface.ranking.Reranker

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
