# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.huggingface.sentence_similarity
from nodetool.workflows.base_node import BaseNode


class SentenceSimilarity(
    SingleOutputGraphNode[types.NPArray], GraphNode[types.NPArray]
):
    """

    Generates dense vector embeddings from text for semantic similarity comparisons.
    text, sentence-similarity, embeddings, NLP, semantic-search

    Use cases:
    - Compute semantic similarity between sentences or documents
    - Build semantic search and recommendation engines
    - Detect duplicate or near-duplicate content
    - Cluster documents by meaning rather than keywords
    - Create text embeddings for downstream ML tasks
    """

    model: types.HFSentenceSimilarity | OutputHandle[types.HFSentenceSimilarity] = (
        connect_field(
            default=types.HFSentenceSimilarity(
                type="hf.sentence_similarity",
                repo_id="",
                path=None,
                variant=None,
                allow_patterns=None,
                ignore_patterns=None,
            ),
            description="The sentence embedding model. all-mpnet-base-v2 offers high quality; MiniLM variants are faster; BGE-m3 is multilingual.",
        )
    )
    inputs: str | OutputHandle[str] = connect_field(
        default="",
        description="The text to generate embeddings for. Can be a sentence, paragraph, or short document.",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.huggingface.sentence_similarity.SentenceSimilarity

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
