# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.huggingface.text_to_3d
from nodetool.workflows.base_node import BaseNode


class ShapETextTo3D(
    SingleOutputGraphNode[types.Model3DRef], GraphNode[types.Model3DRef]
):
    """

    Generate 3D models from text descriptions using OpenAI Shap-E.
    3d, generation, text-to-3d, shap-e, mesh, local

    Use cases:
    - Generate 3D models from text descriptions locally
    - Create 3D assets without API costs
    - Prototype 3D content quickly
    - Generate simple 3D objects for games/visualization

    **Platforms:** all (CPU/MPS/CUDA).

    **Note:** Requires diffusers and torch. First run will download the model (~2.5GB).
    """

    prompt: str | OutputHandle[str] = connect_field(
        default="a shark", description="Text description of the 3D model to generate"
    )
    guidance_scale: float | OutputHandle[float] = connect_field(
        default=15.0,
        description="How strongly to follow the prompt. Higher = more prompt adherence.",
    )
    num_inference_steps: int | OutputHandle[int] = connect_field(
        default=64,
        description="Number of denoising steps. More steps = better quality but slower.",
    )
    frame_size: int | OutputHandle[int] = connect_field(
        default=256,
        description="Resolution of the internal representation. Higher = more detail.",
    )
    seed: int | OutputHandle[int] = connect_field(
        default=-1, description="Random seed for reproducibility. -1 for random."
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.huggingface.text_to_3d.ShapETextTo3D

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
