# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.huggingface.text_to_speech
from nodetool.workflows.base_node import BaseNode


class Bark(SingleOutputGraphNode[types.AudioRef], GraphNode[types.AudioRef]):
    """

    Generates realistic multilingual speech and non-verbal audio from text using Suno's Bark model.
    tts, audio, speech, huggingface, multilingual, voice-synthesis

    Use cases:
    - Create natural-sounding voice content for apps and videos
    - Generate multilingual speech for global applications
    - Produce expressive speech with emotions (laughing, sighing, crying)
    - Add realistic voice to chatbots and virtual assistants
    - Create audio content with background music and sound effects
    """

    model: types.HFTextToSpeech | OutputHandle[types.HFTextToSpeech] = connect_field(
        default=types.HFTextToSpeech(
            type="hf.text_to_speech",
            repo_id="",
            path=None,
            variant=None,
            allow_patterns=None,
            ignore_patterns=None,
        ),
        description="The Bark model variant. bark-small is faster; bark offers higher quality. Both support multilingual output.",
    )
    prompt: str | OutputHandle[str] = connect_field(
        default="",
        description="The text to convert to speech. Can include non-verbal markers like [laughs] or [sighs].",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.huggingface.text_to_speech.Bark

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.huggingface.text_to_speech
from nodetool.workflows.base_node import BaseNode


class KokoroTTS(
    GraphNode[nodetool.nodes.huggingface.text_to_speech.KokoroTTS.OutputType]
):
    """

    Generates high-quality speech from text using the lightweight Kokoro TTS model.
    tts, audio, speech, huggingface, kokoro, multilingual, voice

    Use cases:
    - Generate natural-sounding speech for applications and assistants
    - Create voice content with multiple voice options and styles
    - Build low-latency TTS systems for real-time applications
    - Produce multilingual speech in various languages
    - Generate narration for videos, presentations, and e-learning

    **Note:** Kokoro is a fast, lightweight model (~82M params) with Apache-2.0 license.
    See https://huggingface.co/hexgrad/Kokoro-82M for voice samples.
    """

    LanguageCode: typing.ClassVar[type] = (
        nodetool.nodes.huggingface.text_to_speech.KokoroTTS.LanguageCode
    )
    Voice: typing.ClassVar[type] = (
        nodetool.nodes.huggingface.text_to_speech.KokoroTTS.Voice
    )

    model: types.HFTextToSpeech | OutputHandle[types.HFTextToSpeech] = connect_field(
        default=types.HFTextToSpeech(
            type="hf.text_to_speech",
            repo_id="hexgrad/Kokoro-82M",
            path=None,
            variant=None,
            allow_patterns=None,
            ignore_patterns=None,
        ),
        description="The Kokoro model repository.",
    )
    text: str | OutputHandle[str] = connect_field(
        default="Hello from Kokoro.", description="The text to convert to speech."
    )
    lang_code: nodetool.nodes.huggingface.text_to_speech.KokoroTTS.LanguageCode = Field(
        default=nodetool.nodes.huggingface.text_to_speech.KokoroTTS.LanguageCode.AMERICAN_ENGLISH,
        description="Language for pronunciation. Choose based on your text's language.",
    )
    voice: nodetool.nodes.huggingface.text_to_speech.KokoroTTS.Voice = Field(
        default=nodetool.nodes.huggingface.text_to_speech.KokoroTTS.Voice.AF_HEART,
        description="The voice to use. af_* = American female, am_* = American male, bf_* = British female, etc.",
    )
    speed: float | OutputHandle[float] = connect_field(
        default=1.0,
        description="Speech speed multiplier: 0.5 = half speed, 1.0 = normal, 2.0 = double speed.",
    )

    @property
    def out(self) -> "KokoroTTSOutputs":
        return KokoroTTSOutputs(self)

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.huggingface.text_to_speech.KokoroTTS

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


class KokoroTTSOutputs(OutputsProxy):
    @property
    def audio(self) -> OutputHandle[typing.Any]:
        return typing.cast(OutputHandle[typing.Any], self["audio"])

    @property
    def chunk(self) -> OutputHandle[typing.Any]:
        return typing.cast(OutputHandle[typing.Any], self["chunk"])


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.huggingface.text_to_speech
from nodetool.workflows.base_node import BaseNode


class TextToSpeech(SingleOutputGraphNode[types.AudioRef], GraphNode[types.AudioRef]):
    """

    Converts text to speech using various Hugging Face TTS models for multiple languages.
    tts, audio, speech, huggingface, voice, speak

    Use cases:
    - Generate speech from text for applications and websites
    - Create voice content for virtual assistants and chatbots
    - Produce audio narrations for videos and presentations
    - Build accessibility features with text-to-speech output
    - Generate multilingual speech using MMS-TTS models
    """

    model: types.HFTextToSpeech | OutputHandle[types.HFTextToSpeech] = connect_field(
        default=types.HFTextToSpeech(
            type="hf.text_to_speech",
            repo_id="",
            path=None,
            variant=None,
            allow_patterns=None,
            ignore_patterns=None,
        ),
        description="The TTS model to use. facebook/mms-tts-* models support many languages (eng=English, fra=French, deu=German, kor=Korean, etc.).",
    )
    text: str | OutputHandle[str] = connect_field(
        default="Hello, this is a test of the text-to-speech system.",
        description="The text to convert to speech.",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.huggingface.text_to_speech.TextToSpeech

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
