# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.huggingface.token_classification
from nodetool.workflows.base_node import BaseNode


class TokenClassification(
    SingleOutputGraphNode[types.DataframeRef], GraphNode[types.DataframeRef]
):
    """

    Performs token classification tasks such as Named Entity Recognition (NER).
    text, token classification, named entity recognition, natural language processing

    Use cases:
    - Named Entity Recognition in text
    - Part-of-speech tagging
    - Chunking and shallow parsing
    - Information extraction from unstructured text
    """

    AggregationStrategy: typing.ClassVar[type] = (
        nodetool.nodes.huggingface.token_classification.TokenClassification.AggregationStrategy
    )

    model: types.HFTokenClassification | OutputHandle[types.HFTokenClassification] = (
        connect_field(
            default=types.HFTokenClassification(
                type="hf.token_classification",
                repo_id="dbmdz/bert-large-cased-finetuned-conll03-english",
                path=None,
                variant=None,
                allow_patterns=["*.bin", "*.json", "**/*.json", "*.safetensors"],
                ignore_patterns=None,
            ),
            description="The model ID to use for token classification",
        )
    )
    inputs: str | OutputHandle[str] = connect_field(
        default="", description="The input text for token classification"
    )
    aggregation_strategy: (
        nodetool.nodes.huggingface.token_classification.TokenClassification.AggregationStrategy
    ) = Field(
        default=nodetool.nodes.huggingface.token_classification.TokenClassification.AggregationStrategy.SIMPLE,
        description="Strategy to aggregate tokens into entities",
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.huggingface.token_classification.TokenClassification

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
