# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.huggingface.translation
from nodetool.workflows.base_node import BaseNode


class Translation(SingleOutputGraphNode[str], GraphNode[str]):
    """

    Translates text between languages using sequence-to-sequence transformer models.
    text, translation, NLP, multilingual, localization

    Use cases:
    - Translate content for multilingual websites and applications
    - Enable cross-language communication in chat systems
    - Localize documents and product descriptions
    - Build multilingual content pipelines
    - Support international user bases with automatic translation

    **Note:** Different models support different language pairs. T5 models handle many language combinations.
    """

    LanguageCode: typing.ClassVar[type] = (
        nodetool.nodes.huggingface.translation.Translation.LanguageCode
    )
    LanguageCode: typing.ClassVar[type] = (
        nodetool.nodes.huggingface.translation.Translation.LanguageCode
    )

    model: types.HFTranslation | OutputHandle[types.HFTranslation] = connect_field(
        default=types.HFTranslation(
            type="hf.translation",
            repo_id="google-t5/t5-base",
            path=None,
            variant=None,
            allow_patterns=["*.json", "*.txt", "*.safetensors"],
            ignore_patterns=None,
        ),
        description="The translation model. T5 models support many language pairs; larger variants offer better quality.",
    )
    inputs: str | OutputHandle[str] = connect_field(
        default="", description="The text to translate."
    )
    source_lang: nodetool.nodes.huggingface.translation.Translation.LanguageCode = (
        Field(
            default=nodetool.nodes.huggingface.translation.Translation.LanguageCode.ENGLISH,
            description="The language of the input text.",
        )
    )
    target_lang: nodetool.nodes.huggingface.translation.Translation.LanguageCode = (
        Field(
            default=nodetool.nodes.huggingface.translation.Translation.LanguageCode.FRENCH,
            description="The language to translate the text into.",
        )
    )

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.huggingface.translation.Translation

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()
